version: ~> 1.0

env:
  global:
    # Doctr deploy key for pcdshub/archstats
    - secure: "fmyE7l0lyX+xJtrIVfboqn2/DWgqAFpBZ1gBjXZZ1FX+v8eb7XHd2IIfaUFHwOkX/bYO5LapLtL1K5W34terEmiuXlmj1m4MYc7BVEhtqKjk14Q4hx1BGmR5+YEBKuUkOqN4AIKuW1Z4nvnWzMN8nLymBAoGSvx400UBJyKM3OWTz7MGWRAvFr3nDBBOIELwDDNQDdTeeL88HLGchksWEJf+dEIIlKJuFvlIDQwGZ8xlbXkXVbXPB1L6BMB62DT4SjB8fIMqs83ro8Gn6ii3tHW1LkKvyujermMpGUiRxr/MWrMSnZzj5a0O+IErfr1l/KOjUiAp16RrmQdFhC9X0A3UgzX8EVRkjBNDdG28+oWgqzfEck03CJotb0HDJPpksgO/lN3JszFHnNssq0AN9vBufDy5xe/Wqo2iXZJikqzVr6yluY3yro55kC9uIOgofZOwWsC7EF+Ggq83kqEUPVPJ2mvQxJZi5wQ7DSVPzxpwy1DVayXlNbY1POxbPcdv/mZe6B6H2kTR5b0QK5PI7ViATqlADx8zrxzdbSXvEOwIABZNs4jOIWpwBJ//qIRUcTE2IaDvEWy8l7L0dwvHL3qUrDf0aXKkCV97gFMvoTovCMaVrAoai5gezs4rY6jbCzi9gx/9VfvPz1v0YxG250SXw89mVwmCFz3WkNE+R4w="
    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="docs-requirements.txt dev-requirements.txt requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="archstats"

    # The name of the conda package
    - CONDA_PACKAGE="archstats"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"

    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"
    # Extra dependencies needed to run the tests which are not included
    # at the recipe and dev-requirements.txt.
    - CONDA_EXTRAS=""

    # Extra dependencies needed to run the test with Pip
    - PIP_EXTRAS=""


import:
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda.yml
