{% set data = load_setup_py_data() %}

package:
    name: archstats
    version: {{ data.get('version') }}

source:
    path: ..

build:
    number: 2
    noarch: python

requirements:
    build:
      - python >=3.6
      - setuptools
    run:
      - python >=3.6
      - aiohttp
      - caproto >=0.7.1
      - elasticsearch >=7.8.0
      - inflection

test:
    imports:
      - archstats
    requires:
      - pytest

about:
  home: https://github.com/pcdshub/archstats
  license: SLAC Open License
  summary: EPICS Archiver Appliance statistics IOC
